services:
  - type: web
    name: plant-disease-detector
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
build:
  commands:
    - pip install -r requirements.txt
    - pip install gdown
    - python download_dataset.py
